services:
  mongo-db:
    image: "mongo:latest"
    volumes:
      - mongodbvol:/data/db
  todo:
    image: iti-todo-app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - src.env
    ports:
      - 5000:5000    
volumes:
  mongodbvol:

networks:


