name: docker

on:
  push:
    tags:
    - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
      DOCKER_TAG: ${GITHUB_REF#refs/tags/}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t husseingalal/todo:$DOCKER_TAG .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: husseingalal/todo:$DOCKER_TAG
